on:
  push

name: My Workflow

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:


    - name: Rest API Call
      uses: jirikuncar/recorder
      with:
        endpoint: https://reqres.in/api/users?page=2
        jq: '.[0]'
    - run: echo -e "${{ steps.stars.outputs.response }}"

        